/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicTechnologyRouteImport } from './routes/_public/technology'
import { Route as PublicSupportRouteImport } from './routes/_public/support'
import { Route as PublicStoryRouteImport } from './routes/_public/story'
import { Route as PublicProfileRouteImport } from './routes/_public/profile'
import { Route as PublicOrderConfirmedRouteImport } from './routes/_public/order-confirmed'
import { Route as PublicCollectionRouteImport } from './routes/_public/collection'
import { Route as PublicCheckoutRouteImport } from './routes/_public/checkout'
import { Route as PublicCartRouteImport } from './routes/_public/cart'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as PublicProductsSlugRouteImport } from './routes/_public/products/$slug'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTechnologyRoute = PublicTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSupportRoute = PublicSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicStoryRoute = PublicStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicOrderConfirmedRoute = PublicOrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCollectionRoute = PublicCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCheckoutRoute = PublicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCartRoute = PublicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicProductsSlugRoute = PublicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/cart': typeof PublicCartRoute
  '/checkout': typeof PublicCheckoutRoute
  '/collection': typeof PublicCollectionRoute
  '/order-confirmed': typeof PublicOrderConfirmedRoute
  '/profile': typeof PublicProfileRoute
  '/story': typeof PublicStoryRoute
  '/support': typeof PublicSupportRoute
  '/technology': typeof PublicTechnologyRoute
  '/terms': typeof PublicTermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/products/$slug': typeof PublicProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/cart': typeof PublicCartRoute
  '/checkout': typeof PublicCheckoutRoute
  '/collection': typeof PublicCollectionRoute
  '/order-confirmed': typeof PublicOrderConfirmedRoute
  '/profile': typeof PublicProfileRoute
  '/story': typeof PublicStoryRoute
  '/support': typeof PublicSupportRoute
  '/technology': typeof PublicTechnologyRoute
  '/terms': typeof PublicTermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/products/$slug': typeof PublicProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/cart': typeof PublicCartRoute
  '/_public/checkout': typeof PublicCheckoutRoute
  '/_public/collection': typeof PublicCollectionRoute
  '/_public/order-confirmed': typeof PublicOrderConfirmedRoute
  '/_public/profile': typeof PublicProfileRoute
  '/_public/story': typeof PublicStoryRoute
  '/_public/support': typeof PublicSupportRoute
  '/_public/technology': typeof PublicTechnologyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/_public/products/$slug': typeof PublicProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/order-confirmed'
    | '/profile'
    | '/story'
    | '/support'
    | '/technology'
    | '/terms'
    | '/admin/dashboard'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/order-confirmed'
    | '/profile'
    | '/story'
    | '/support'
    | '/technology'
    | '/terms'
    | '/admin/dashboard'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/admin'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_public/cart'
    | '/_public/checkout'
    | '/_public/collection'
    | '/_public/order-confirmed'
    | '/_public/profile'
    | '/_public/story'
    | '/_public/support'
    | '/_public/technology'
    | '/_public/terms'
    | '/admin/dashboard'
    | '/_public/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/technology': {
      id: '/_public/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof PublicTechnologyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/support': {
      id: '/_public/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PublicSupportRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/story': {
      id: '/_public/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof PublicStoryRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/profile': {
      id: '/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/order-confirmed': {
      id: '/_public/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof PublicOrderConfirmedRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/collection': {
      id: '/_public/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof PublicCollectionRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/checkout': {
      id: '/_public/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicCheckoutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/cart': {
      id: '/_public/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicCartRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/products/$slug': {
      id: '/_public/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof PublicProductsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicCartRoute: typeof PublicCartRoute
  PublicCheckoutRoute: typeof PublicCheckoutRoute
  PublicCollectionRoute: typeof PublicCollectionRoute
  PublicOrderConfirmedRoute: typeof PublicOrderConfirmedRoute
  PublicProfileRoute: typeof PublicProfileRoute
  PublicStoryRoute: typeof PublicStoryRoute
  PublicSupportRoute: typeof PublicSupportRoute
  PublicTechnologyRoute: typeof PublicTechnologyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicProductsSlugRoute: typeof PublicProductsSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCartRoute: PublicCartRoute,
  PublicCheckoutRoute: PublicCheckoutRoute,
  PublicCollectionRoute: PublicCollectionRoute,
  PublicOrderConfirmedRoute: PublicOrderConfirmedRoute,
  PublicProfileRoute: PublicProfileRoute,
  PublicStoryRoute: PublicStoryRoute,
  PublicSupportRoute: PublicSupportRoute,
  PublicTechnologyRoute: PublicTechnologyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicProductsSlugRoute: PublicProductsSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
